# H2 console (accessible at /api/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL logging
spring.jpa.show-sql=true

# Set to false to disable background seeding (e.g for dev use)
slop.seed.enabled=false