package com.bantar.db.migration;

import com.bantar.db.migration.tools.DatabaseMigrationHelper;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;

@SuppressWarnings("unused")
public class V10__Insert_initial_debates extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();

        DatabaseMigrationHelper.batchInsertIntoTable(
                connection, "DEBATE", "ID, TEXT",
                "(1, 'Should governments implement universal basic income?')",
                "(2, 'Is artificial intelligence a greater threat or benefit to humanity?')",
                "(3, 'Should the use of fossil fuels be banned within the next 20 years?')",
                "(4, 'Is online learning more effective than traditional classroom education?')",
                "(5, 'Should social media platforms be held responsible for misinformation?')",
                "(6, 'Would mandatory military service improve national unity?')",
                "(7, 'Should genetic editing in humans be legal for disease prevention?')",
                "(8, 'Is homework beneficial for student learning?')",
                "(9, 'Should developing countries prioritize economic growth over environmental protection?')",
                "(10, 'Is remote work the future of employment?')",
                "(11, 'Should voting be mandatory in democratic countries?')",
                "(12, 'Is space exploration worth the cost?')",
                "(13, 'Should the death penalty be abolished worldwide?')",
                "(14, 'Are video games harmful or helpful to youth development?')",
                "(15, 'Should the government regulate social media content?')",
                "(16, 'Is globalization beneficial or harmful to local cultures?')",
                "(17, 'Should animals be used for scientific testing?')",
                "(18, 'Is climate change the greatest threat facing humanity today?')",
                "(19, 'Should college education be free for all citizens?')",
                "(20, 'Is censorship ever justified in modern society?')",
                "(21, 'Should billionaires exist in an equitable society?')",
                "(22, 'Is nuclear energy a sustainable solution for the future?')",
                "(23, 'Should smartphones be banned in classrooms?')",
                "(24, 'Is genetic cloning ethical?')",
                "(25, 'Should advertising to children be restricted or banned?')",
                "(26, 'Is homeschooling more effective than public schooling?')",
                "(27, 'Should countries open their borders to refugees freely?')",
                "(28, 'Is the internet making us smarter or lazier?')",
                "(29, 'Should military spending be reduced to fund social programs?')",
                "(30, 'Is animal agriculture the leading cause of climate change?')",
                "(31, 'Should voting age be lowered to 16?')",
                "(32, 'Are standardized tests an accurate measure of intelligence?')",
                "(33, 'Should humans attempt to colonize Mars?')",
                "(34, 'Is privacy more important than national security?')",
                "(35, 'Should recreational drugs be legalized globally?')",
                "(36, 'Are electric vehicles truly environmentally friendly?')",
                "(37, 'Should school uniforms be mandatory?')",
                "(38, 'Is artificial intelligence capable of true creativity?')",
                "(39, 'Should public transportation be free?')",
                "(40, 'Is patriotism a virtue or a vice?')",
                "(41, 'Should companies be allowed to collect user data for profit?')",
                "(42, 'Is animal rights more important than cultural traditions?')",
                "(43, 'Should history education be revised to remove national bias?')",
                "(44, 'Is space colonization morally justifiable?')",
                "(45, 'Should athletes be required to represent their birth countries?')",
                "(46, 'Is remote work reducing workplace innovation?')",
                "(47, 'Should governments ban the use of plastic entirely?')",
                "(48, 'Is modern art still art?')",
                "(49, 'Should the wealthy pay higher taxes to support the poor?')",
                "(50, 'Is surveillance technology necessary for safety?')",
                "(51, 'Should parents be held legally responsible for children''s crimes?')",
                "(52, 'Is globalization erasing cultural identity?')",
                "(53, 'Should voting be allowed online?')",
                "(54, 'Is AI-generated art real art?')",
                "(55, 'Should the minimum wage be tied to inflation?')",
                "(56, 'Is it ethical to consume meat in the modern world?')",
                "(57, 'Should zoos be banned?')",
                "(58, 'Is standardized education killing creativity?')",
                "(59, 'Should influencers be regulated like journalists?')",
                "(60, 'Is cancel culture beneficial or harmful to society?')",
                "(61, 'Should space tourism be restricted for environmental reasons?')",
                "(62, 'Is democracy the best form of government?')",
                "(63, 'Should schools replace textbooks with tablets?')",
                "(64, 'Is it ethical to use AI for emotional companionship?')",
                "(65, 'Should nuclear weapons be completely eliminated?')",
                "(66, 'Is homeschooling isolating children from real-world skills?')",
                "(67, 'Should celebrities be role models?')",
                "(68, 'Is globalization creating economic inequality?')",
                "(69, 'Should public healthcare be a universal right?')",
                "(70, 'Is virtual reality changing human connection?')",
                "(71, 'Should fashion brands be responsible for labor conditions?')",
                "(72, 'Is climate activism too radical or not radical enough?')",
                "(73, 'Should the arts be prioritized in education?')",
                "(74, 'Is space exploration a waste of money?')",
                "(75, 'Should humans prioritize Mars colonization over Earth conservation?')",
                "(76, 'Is social media helping or hurting democracy?')",
                "(77, 'Should governments regulate AI algorithms?')",
                "(78, 'Is censorship necessary for social stability?')",
                "(79, 'Should renewable energy replace all fossil fuels by 2050?')",
                "(80, 'Is universal healthcare economically feasible?')",
                "(81, 'Should homework be abolished entirely?')",
                "(82, 'Is AI more likely to create or destroy jobs?')",
                "(83, 'Should parental leave be mandatory worldwide?')",
                "(84, 'Is space militarization a threat to humanity?')",
                "(85, 'Should genetically modified food be banned?')",
                "(86, 'Is online privacy more important than convenience?')",
                "(87, 'Should children be taught coding from an early age?')",
                "(88, 'Is modern democracy failing?')",
                "(89, 'Should AI be granted legal personhood?')",
                "(90, 'Is capitalism the best economic system?')",
                "(91, 'Should recreational cannabis be legalized everywhere?')",
                "(92, 'Is the gig economy harmful to workers?')",
                "(93, 'Should governments regulate cryptocurrencies?')",
                "(94, 'Is veganism a moral obligation?')",
                "(95, 'Should space mining be allowed?')",
                "(96, 'Is competition or collaboration better for society?')",
                "(97, 'Should public transport be fully automated?')",
                "(98, 'Is homeschooling better for gifted children?')",
                "(99, 'Should humans attempt immortality through technology?')",
                "(100, 'Is fast fashion ethically wrong?')");

        DatabaseMigrationHelper.batchInsertIntoTable(
                connection,
                "DEBATE_CATEGORY", "DEBATE_ID, CATEGORY_CODE",
                "(1, 'DEBATE'), (1, 'POLICY')",
                "(2, 'DEBATE'), (2, 'TECHNOLOGY')",
                "(3, 'DEBATE'), (3, 'ENVIRONMENT')",
                "(4, 'DEBATE'), (4, 'EDUCATION')",
                "(5, 'DEBATE'), (5, 'POLICY')",
                "(6, 'DEBATE'), (6, 'CASUAL')",
                "(7, 'DEBATE'), (7, 'ETHICS')",
                "(8, 'DEBATE'), (8, 'EDUCATION')",
                "(9, 'DEBATE'), (9, 'ENVIRONMENT')",
                "(10, 'DEBATE'), (10, 'TECHNOLOGY')",
                "(11, 'DEBATE'), (11, 'POLICY')",
                "(12, 'DEBATE'), (12, 'TECHNOLOGY')",
                "(13, 'DEBATE'), (13, 'ETHICS')",
                "(14, 'DEBATE'), (14, 'CASUAL')",
                "(15, 'DEBATE'), (15, 'POLICY')",
                "(16, 'DEBATE'), (16, 'CASUAL')",
                "(17, 'DEBATE'), (17, 'ETHICS')",
                "(18, 'DEBATE'), (18, 'ENVIRONMENT')",
                "(19, 'DEBATE'), (19, 'EDUCATION')",
                "(20, 'DEBATE'), (20, 'TECHNOLOGY')",
                "(21, 'DEBATE'), (21, 'POLICY')",
                "(22, 'DEBATE'), (22, 'ENVIRONMENT')",
                "(23, 'DEBATE'), (23, 'EDUCATION')",
                "(24, 'DEBATE'), (24, 'ETHICS')",
                "(25, 'DEBATE'), (25, 'EDUCATION')",
                "(26, 'DEBATE'), (26, 'POLICY')",
                "(27, 'DEBATE'), (27, 'TECHNOLOGY')",
                "(28, 'DEBATE'), (28, 'ENVIRONMENT')",
                "(29, 'DEBATE'), (29, 'ENVIRONMENT')",
                "(30, 'DEBATE'), (30, 'POLICY')",
                "(31, 'DEBATE'), (31, 'EDUCATION')",
                "(32, 'DEBATE'), (32, 'TECHNOLOGY')",
                "(33, 'DEBATE'), (33, 'POLICY')",
                "(34, 'DEBATE'), (34, 'TECHNOLOGY')",
                "(35, 'DEBATE'), (35, 'ENVIRONMENT')",
                "(36, 'DEBATE'), (36, 'EDUCATION')",
                "(37, 'DEBATE'), (37, 'POLICY')",
                "(38, 'DEBATE'), (38, 'CASUAL')",
                "(39, 'DEBATE'), (39, 'TECHNOLOGY')",
                "(40, 'DEBATE'), (40, 'POLICY')",
                "(41, 'DEBATE'), (41, 'ETHICS')",
                "(42, 'DEBATE'), (42, 'EDUCATION')",
                "(43, 'DEBATE'), (43, 'TECHNOLOGY')",
                "(44, 'DEBATE'), (44, 'CASUAL')",
                "(45, 'DEBATE'), (45, 'ETHICS')",
                "(46, 'DEBATE'), (46, 'POLICY')",
                "(47, 'DEBATE'), (47, 'TECHNOLOGY')",
                "(48, 'DEBATE'), (48, 'EDUCATION')",
                "(49, 'DEBATE'), (49, 'ENVIRONMENT')",
                "(50, 'DEBATE'), (50, 'EDUCATION')",
                "(51, 'DEBATE'), (51, 'POLICY')",
                "(52, 'DEBATE'), (52, 'TECHNOLOGY')",
                "(53, 'DEBATE'), (53, 'ETHICS')",
                "(54, 'DEBATE'), (54, 'ENVIRONMENT')",
                "(55, 'DEBATE'), (55, 'EDUCATION')",
                "(56, 'DEBATE'), (56, 'CASUAL')",
                "(57, 'DEBATE'), (57, 'TECHNOLOGY')",
                "(58, 'DEBATE'), (58, 'ENVIRONMENT')",
                "(59, 'DEBATE'), (59, 'EDUCATION')",
                "(60, 'DEBATE'), (60, 'TECHNOLOGY')",
                "(61, 'DEBATE'), (61, 'POLICY')",
                "(62, 'DEBATE'), (62, 'ETHICS')",
                "(63, 'DEBATE'), (63, 'ENVIRONMENT')",
                "(64, 'DEBATE'), (64, 'EDUCATION')",
                "(65, 'DEBATE'), (65, 'CASUAL')",
                "(66, 'DEBATE'), (66, 'POLICY')",
                "(67, 'DEBATE'), (67, 'TECHNOLOGY')",
                "(68, 'DEBATE'), (68, 'ETHICS')",
                "(69, 'DEBATE'), (69, 'ENVIRONMENT')",
                "(70, 'DEBATE'), (70, 'EDUCATION')",
                "(71, 'DEBATE'), (71, 'TECHNOLOGY')",
                "(72, 'DEBATE'), (72, 'CASUAL')",
                "(73, 'DEBATE'), (73, 'ETHICS')",
                "(74, 'DEBATE'), (74, 'POLICY')",
                "(75, 'DEBATE'), (75, 'ENVIRONMENT')",
                "(76, 'DEBATE'), (76, 'EDUCATION')",
                "(77, 'DEBATE'), (77, 'TECHNOLOGY')",
                "(78, 'DEBATE'), (78, 'ETHICS')",
                "(79, 'DEBATE'), (79, 'POLICY')",
                "(80, 'DEBATE'), (80, 'CASUAL')",
                "(81, 'DEBATE'), (81, 'TECHNOLOGY')",
                "(82, 'DEBATE'), (82, 'ENVIRONMENT')",
                "(83, 'DEBATE'), (83, 'EDUCATION')",
                "(84, 'DEBATE'), (84, 'TECHNOLOGY')",
                "(85, 'DEBATE'), (85, 'ETHICS')",
                "(86, 'DEBATE'), (86, 'CASUAL')",
                "(87, 'DEBATE'), (87, 'POLICY')",
                "(88, 'DEBATE'), (88, 'ENVIRONMENT')",
                "(89, 'DEBATE'), (89, 'EDUCATION')",
                "(90, 'DEBATE'), (90, 'TECHNOLOGY')",
                "(91, 'DEBATE'), (91, 'ETHICS')",
                "(92, 'DEBATE'), (92, 'POLICY')",
                "(93, 'DEBATE'), (93, 'TECHNOLOGY')",
                "(94, 'DEBATE'), (94, 'ENVIRONMENT')",
                "(95, 'DEBATE'), (95, 'EDUCATION')",
                "(96, 'DEBATE'), (96, 'CASUAL')",
                "(97, 'DEBATE'), (97, 'POLICY')",
                "(98, 'DEBATE'), (98, 'TECHNOLOGY')",
                "(99, 'DEBATE'), (99, 'ETHICS')",
                "(100, 'DEBATE'), (100, 'CASUAL')");

    }
}
