package com.bantar.db.migration;

import com.bantar.db.tools.DatabaseMigrationHelper;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

@SuppressWarnings("unused")
public class V14__Create_Mind_Reader_Table extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        String createTableSQL = "CREATE TABLE MIND_READER (" +
                "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "TEXT VARCHAR(500) NOT NULL" +
                ")";
        DatabaseMigrationHelper.createTableIfNotExists(context.getConnection(), "MIND_READER", createTableSQL);
    }
}
