package com.bantar.db.migration;

import com.bantar.db.tools.DatabaseMigrationHelper;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

@SuppressWarnings("unused")
public class V15__Create_Mind_Reader_Category_Table extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        String createTableSQL = "CREATE TABLE MIND_READER_CATEGORY (" +
                "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "CATEGORY_CODE VARCHAR(100) NOT NULL, " +
                "MIND_READER_ID INT NOT NULL, " +
                "CONSTRAINT FK_MIND_READER FOREIGN KEY (MIND_READER_ID) REFERENCES MIND_READER(ID), " +
                "CONSTRAINT UNIQUE_MIND_READER_CATEGORY UNIQUE (MIND_READER_ID, CATEGORY_CODE)" +
                ")";
        DatabaseMigrationHelper.createTableIfNotExists(context.getConnection(), "MIND_READER_CATEGORY", createTableSQL);
    }
}
