package com.bantar.db.migration;

import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

import java.sql.Connection;
import java.sql.Statement;

@SuppressWarnings("unused")
public class V1__Create_Initial_Schema extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        Connection connection = context.getConnection();

        try (Statement stmt = connection.createStatement()) {
            stmt.execute("CREATE TABLE ICEBREAKER (" +
                    "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "TEXT VARCHAR(500)" +
                    ")");

            stmt.execute("CREATE TABLE ICEBREAKER_CATEGORY (" +
                    "QUESTION_CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT, " +
                    "QUESTION_ID INT NOT NULL, " +
                    "CATEGORY_CODE VARCHAR(100), " +
                    "CONSTRAINT FK_QUESTION FOREIGN KEY (QUESTION_ID) REFERENCES ICEBREAKER(ID), " +
                    "CONSTRAINT UNIQUE_QUESTION_CATEGORY UNIQUE (QUESTION_ID, CATEGORY_CODE)" +
                    ")");

            stmt.execute("CREATE TABLE DEBATE (" +
                    "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "TEXT VARCHAR(500)" +
                    ")");

            stmt.execute("CREATE TABLE DEBATE_CATEGORY (" +
                    "DEBATE_CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT, " +
                    "DEBATE_ID INT NOT NULL, " +
                    "CATEGORY_CODE VARCHAR(100), " +
                    "CONSTRAINT FK_DEBATE FOREIGN KEY (DEBATE_ID) REFERENCES DEBATE(ID), " +
                    "CONSTRAINT UNIQUE_DEBATE_CATEGORY UNIQUE (DEBATE_ID, CATEGORY_CODE)" +
                    ")");

            stmt.execute("CREATE TABLE MIND_READER (" +
                    "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "TEXT VARCHAR(500) NOT NULL" +
                    ")");

            stmt.execute("CREATE TABLE MIND_READER_CATEGORY (" +
                    "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "CATEGORY_CODE VARCHAR(100) NOT NULL, " +
                    "MIND_READER_ID INT NOT NULL, " +
                    "CONSTRAINT FK_MIND_READER FOREIGN KEY (MIND_READER_ID) REFERENCES MIND_READER(ID), " +
                    "CONSTRAINT UNIQUE_MIND_READER_CATEGORY UNIQUE (MIND_READER_ID, CATEGORY_CODE)" +
                    ")");

            stmt.execute("CREATE TABLE TOPLIST (" +
                    "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "TEXT VARCHAR(500)" +
                    ")");

            stmt.execute("CREATE TABLE TOPLIST_CATEGORY (" +
                    "TOPLIST_CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT, " +
                    "TOPLIST_ID INT NOT NULL, " +
                    "CATEGORY_CODE VARCHAR(100), " +
                    "CONSTRAINT FK_TOPLIST FOREIGN KEY (TOPLIST_ID) REFERENCES TOPLIST(ID), " +
                    "CONSTRAINT UNIQUE_TOPLIST_CATEGORY UNIQUE (TOPLIST_ID, CATEGORY_CODE)" +
                    ")");

            stmt.execute("CREATE TABLE AI_QUESTION (" +
                    "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "TEXT VARCHAR(500) NOT NULL, " +
                    "HASH VARCHAR(64) NOT NULL, " +
                    "CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                    "CONSTRAINT UNIQUE_AI_QUESTION_HASH UNIQUE (HASH)" +
                    ")");

            stmt.execute("CREATE TABLE EVENT (" +
                    "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "NAME VARCHAR(500) NOT NULL, " +
                    "FRIENDLY_NAME VARCHAR(500) NOT NULL, " +
                    "STYLE TEXT, " +
                    "TYPE INTEGER NOT NULL, " +
                    "FROM_DATE DATE, " +
                    "UNTIL_DATE DATE, " +
                    "DATES_JSON TEXT, " +
                    "DAYS_OF_WEEK_JSON TEXT, " +
                    "IS_DELETED BOOLEAN DEFAULT 0" +
                    ")");

            stmt.execute("CREATE TABLE EVENT_QUESTIONS (" +
                    "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "TEXT VARCHAR(500) NOT NULL, " +
                    "EVENT_ID INT NOT NULL, " +
                    "CONSTRAINT FK_EVENT_QUESTIONS_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID)" +
                    ")");
        }
    }
}
