package com.bantar.db.migration;

import com.bantar.db.tools.DatabaseMigrationHelper;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

@SuppressWarnings("unused")
public class V20__Create_Toplist_Tables extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        String createToplistSQL = "CREATE TABLE TOPLIST (" +
                "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "TEXT VARCHAR(500)" +
                ")";
                
        DatabaseMigrationHelper.createTableIfNotExists(context.getConnection(), "TOPLIST", createToplistSQL);

        String createToplistCategorySQL = "CREATE TABLE TOPLIST_CATEGORY (" +
                "TOPLIST_CATEGORY_ID INT PRIMARY KEY AUTO_INCREMENT, " +
                "TOPLIST_ID INT NOT NULL, " +
                "CATEGORY_CODE VARCHAR(100), " +
                "CONSTRAINT FK_TOPLIST FOREIGN KEY (TOPLIST_ID) REFERENCES TOPLIST(ID), " +
                "CONSTRAINT UNIQUE_TOPLIST_CATEGORY UNIQUE (TOPLIST_ID, CATEGORY_CODE)" +
                ")";

        DatabaseMigrationHelper.createTableIfNotExists(context.getConnection(), "TOPLIST_CATEGORY", createToplistCategorySQL);
    }
}
