package com.bantar.db.migration;

import com.bantar.db.tools.DatabaseMigrationHelper;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

@SuppressWarnings("unused")
public class V23__Add_Event_Table extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {

        String createTableSQL = "CREATE TABLE EVENT (" +
                "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "NAME VARCHAR(500) NOT NULL, " +
                "FRIENDLY_NAME VARCHAR(500) NOT NULL, " +
                "STYLE TEXT, " +
                "TYPE INTEGER NOT NULL, " +
                "FROM_DATE DATE, " +
                "UNTIL_DATE DATE, " +
                "DATES_JSON TEXT, " +
                "DAYS_OF_WEEK_JSON TEXT, " +
                "IS_DELETED BOOLEAN DEFAULT 0" +
                ")";

        DatabaseMigrationHelper.createTableIfNotExists(context.getConnection(), "EVENT", createTableSQL);

        String createEventQuestionsSQL = "CREATE TABLE EVENT_QUESTIONS (" +
                "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "TEXT VARCHAR(500) NOT NULL, " +
                "EVENT_ID INT NOT NULL, " +
                "CONSTRAINT FK_EVENT_QUESTIONS_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID)" +
                ")";

        DatabaseMigrationHelper.createTableIfNotExists(context.getConnection(), "EVENT_QUESTIONS",
                createEventQuestionsSQL);
    }
}
