package com.bantar.db.migration;

import com.bantar.db.DatabaseMigrationHelper;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

@SuppressWarnings("unused")
public class V7__Create_Ai_Question_Table extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        String createTableSQL = "CREATE TABLE AI_QUESTION (" +
                "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "TEXT VARCHAR(500) NOT NULL, " +
                "HASH VARCHAR(64) NOT NULL, " +
                "CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                "CONSTRAINT UNIQUE_AI_QUESTION_HASH UNIQUE (HASH)" +
                ")";
        DatabaseMigrationHelper.createTableIfNotExists(context.getConnection(), "AI_QUESTION", createTableSQL);
    }
}
