package com.bantar.db.migration;

import com.bantar.db.tools.DatabaseMigrationHelper;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

@SuppressWarnings("unused")
public class V8__Create_Debate_Table extends BaseJavaMigration {

    @Override
    public void migrate(Context context) throws Exception {
        String createTableSQL = "CREATE TABLE DEBATE (" +
                "ID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                "TEXT VARCHAR(500)" +
                ")";
        DatabaseMigrationHelper.createTableIfNotExists(context.getConnection(), "DEBATE", createTableSQL);
    }
}
