package com.bantar.seeder;

import com.bantar.model.DebateCategory;
import java.util.List;

final class DebateSeedData {

    record Item(String text, List<DebateCategory> categories) {
    }

    static final List<Item> ITEMS = List.of(
            new Item("Should governments implement universal basic income?", List.of(DebateCategory.POLICY)),
            new Item("Is artificial intelligence a greater threat or benefit to humanity?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Should the use of fossil fuels be banned within the next 20 years?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Is online learning more effective than traditional classroom education?", List.of(DebateCategory.EDUCATION)),
            new Item("Should social media platforms be held responsible for misinformation?", List.of(DebateCategory.POLICY)),
            new Item("Would mandatory military service improve national unity?", List.of(DebateCategory.CASUAL)),
            new Item("Should genetic editing in humans be legal for disease prevention?", List.of(DebateCategory.ETHICS)),
            new Item("Is homework beneficial for student learning?", List.of(DebateCategory.EDUCATION)),
            new Item("Should developing countries prioritize economic growth over environmental protection?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Is remote work the future of employment?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Should voting be mandatory in democratic countries?", List.of(DebateCategory.POLICY)),
            new Item("Is space exploration worth the cost?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Should the death penalty be abolished worldwide?", List.of(DebateCategory.ETHICS)),
            new Item("Are video games harmful or helpful to youth development?", List.of(DebateCategory.CASUAL)),
            new Item("Should the government regulate social media content?", List.of(DebateCategory.POLICY)),
            new Item("Is globalization beneficial or harmful to local cultures?", List.of(DebateCategory.CASUAL)),
            new Item("Should animals be used for scientific testing?", List.of(DebateCategory.ETHICS)),
            new Item("Is climate change the greatest threat facing humanity today?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Should college education be free for all citizens?", List.of(DebateCategory.EDUCATION)),
            new Item("Is censorship ever justified in modern society?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Should billionaires exist in an equitable society?", List.of(DebateCategory.POLICY)),
            new Item("Is nuclear energy a sustainable solution for the future?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Should smartphones be banned in classrooms?", List.of(DebateCategory.EDUCATION)),
            new Item("Is genetic cloning ethical?", List.of(DebateCategory.ETHICS)),
            new Item("Should advertising to children be restricted or banned?", List.of(DebateCategory.EDUCATION)),
            new Item("Is homeschooling more effective than public schooling?", List.of(DebateCategory.POLICY)),
            new Item("Should countries open their borders to refugees freely?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Is the internet making us smarter or lazier?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Should military spending be reduced to fund social programs?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Is animal agriculture the leading cause of climate change?", List.of(DebateCategory.POLICY)),
            new Item("Should voting age be lowered to 16?", List.of(DebateCategory.EDUCATION)),
            new Item("Are standardized tests an accurate measure of intelligence?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Should humans attempt to colonize Mars?", List.of(DebateCategory.POLICY)),
            new Item("Is privacy more important than national security?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Should recreational drugs be legalized globally?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Are electric vehicles truly environmentally friendly?", List.of(DebateCategory.EDUCATION)),
            new Item("Should school uniforms be mandatory?", List.of(DebateCategory.POLICY)),
            new Item("Is artificial intelligence capable of true creativity?", List.of(DebateCategory.CASUAL)),
            new Item("Should public transportation be free?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Is patriotism a virtue or a vice?", List.of(DebateCategory.POLICY)),
            new Item("Should companies be allowed to collect user data for profit?", List.of(DebateCategory.ETHICS)),
            new Item("Is animal rights more important than cultural traditions?", List.of(DebateCategory.EDUCATION)),
            new Item("Should history education be revised to remove national bias?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Is space colonization morally justifiable?", List.of(DebateCategory.CASUAL)),
            new Item("Should athletes be required to represent their birth countries?", List.of(DebateCategory.ETHICS)),
            new Item("Is remote work reducing workplace innovation?", List.of(DebateCategory.POLICY)),
            new Item("Should governments ban the use of plastic entirely?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Is modern art still art?", List.of(DebateCategory.EDUCATION)),
            new Item("Should the wealthy pay higher taxes to support the poor?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Is surveillance technology necessary for safety?", List.of(DebateCategory.EDUCATION)),
            new Item("Should parents be held legally responsible for children's crimes?", List.of(DebateCategory.POLICY)),
            new Item("Is globalization erasing cultural identity?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Should voting be allowed online?", List.of(DebateCategory.ETHICS)),
            new Item("Is AI-generated art real art?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Should the minimum wage be tied to inflation?", List.of(DebateCategory.EDUCATION)),
            new Item("Is it ethical to consume meat in the modern world?", List.of(DebateCategory.CASUAL)),
            new Item("Should zoos be banned?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Is standardized education killing creativity?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Should influencers be regulated like journalists?", List.of(DebateCategory.EDUCATION)),
            new Item("Is cancel culture beneficial or harmful to society?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Should space tourism be restricted for environmental reasons?", List.of(DebateCategory.POLICY)),
            new Item("Is democracy the best form of government?", List.of(DebateCategory.ETHICS)),
            new Item("Should schools replace textbooks with tablets?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Is it ethical to use AI for emotional companionship?", List.of(DebateCategory.EDUCATION)),
            new Item("Should nuclear weapons be completely eliminated?", List.of(DebateCategory.CASUAL)),
            new Item("Is homeschooling isolating children from real-world skills?", List.of(DebateCategory.POLICY)),
            new Item("Should celebrities be role models?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Is globalization creating economic inequality?", List.of(DebateCategory.ETHICS)),
            new Item("Should public healthcare be a universal right?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Is virtual reality changing human connection?", List.of(DebateCategory.EDUCATION)),
            new Item("Should fashion brands be responsible for labor conditions?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Is climate activism too radical or not radical enough?", List.of(DebateCategory.CASUAL)),
            new Item("Should the arts be prioritized in education?", List.of(DebateCategory.ETHICS)),
            new Item("Is space exploration a waste of money?", List.of(DebateCategory.POLICY)),
            new Item("Should humans prioritize Mars colonization over Earth conservation?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Is social media helping or hurting democracy?", List.of(DebateCategory.EDUCATION)),
            new Item("Should governments regulate AI algorithms?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Is censorship necessary for social stability?", List.of(DebateCategory.ETHICS)),
            new Item("Should renewable energy replace all fossil fuels by 2050?", List.of(DebateCategory.POLICY)),
            new Item("Is universal healthcare economically feasible?", List.of(DebateCategory.CASUAL)),
            new Item("Should homework be abolished entirely?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Is AI more likely to create or destroy jobs?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Should parental leave be mandatory worldwide?", List.of(DebateCategory.EDUCATION)),
            new Item("Is space militarization a threat to humanity?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Should genetically modified food be banned?", List.of(DebateCategory.ETHICS)),
            new Item("Is online privacy more important than convenience?", List.of(DebateCategory.CASUAL)),
            new Item("Should children be taught coding from an early age?", List.of(DebateCategory.POLICY)),
            new Item("Is modern democracy failing?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Should AI be granted legal personhood?", List.of(DebateCategory.EDUCATION)),
            new Item("Is capitalism the best economic system?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Should recreational cannabis be legalized everywhere?", List.of(DebateCategory.ETHICS)),
            new Item("Is the gig economy harmful to workers?", List.of(DebateCategory.POLICY)),
            new Item("Should governments regulate cryptocurrencies?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Is veganism a moral obligation?", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Should space mining be allowed?", List.of(DebateCategory.EDUCATION)),
            new Item("Is competition or collaboration better for society?", List.of(DebateCategory.CASUAL)),
            new Item("Should public transport be fully automated?", List.of(DebateCategory.POLICY)),
            new Item("Is homeschooling better for gifted children?", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Should humans attempt immortality through technology?", List.of(DebateCategory.ETHICS)),
            new Item("Is fast fashion ethically wrong?", List.of(DebateCategory.CASUAL)),
            new Item("Governing bodies should protect indigenous languages through formal programs.", List.of(DebateCategory.POLICY)),
            new Item("Legal frameworks must be created for regulation of smart home data collection.", List.of(DebateCategory.POLICY)),
            new Item("Companies should be required to report and reduce microplastic pollution.", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Companies with monopolistic power should be subject to stricter consumer protections.", List.of(DebateCategory.POLICY)),
            new Item("Governments should incentivize renewable energy via targeted subsidies.", List.of(DebateCategory.ENVIRONMENT)),
            new Item("The voting age should be lowered to sixteen in national elections.", List.of(DebateCategory.POLICY)),
            new Item("AI systems used for creative works should disclose human contribution levels.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Ethical limits should govern the use of drones in public spaces.", List.of(DebateCategory.ETHICS)),
            new Item("Schools should prioritize STEM education over arts and humanities.", List.of(DebateCategory.EDUCATION)),
            new Item("Public access to high-quality broadband should be guaranteed as a public good.", List.of(DebateCategory.POLICY)),
            new Item("AI-generated art should be eligible for copyright protection under current law.", List.of(DebateCategory.ETHICS, DebateCategory.TECHNOLOGY)),
            new Item("Public utilities should remain under public control rather than privatized.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Research into safe climate interventions should proceed under strict international oversight.", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Government intervention is required to curb the worst effects of fast fashion.", List.of(DebateCategory.POLICY)),
            new Item("Companies must disclose climate risks in their financial reporting.", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Student loan debt should be forgiven to broaden access to higher education.", List.of(DebateCategory.EDUCATION)),
            new Item("Electric vehicle purchases should receive direct government subsidies.", List.of(DebateCategory.POLICY)),
            new Item("Mandatory vaccination policies are justified during severe public health crises.", List.of(DebateCategory.POLICY)),
            new Item("Public funding for the arts is essential and should be increased.", List.of(DebateCategory.POLICY)),
            new Item("Social media platforms must be required to label AI-generated political content.", List.of(DebateCategory.ETHICS, DebateCategory.TECHNOLOGY)),
            new Item("Governments should provide tax incentives for companies that adopt circular design.", List.of(DebateCategory.POLICY)),
            new Item("Cities should require minimum green space per resident to improve quality of life.", List.of(DebateCategory.POLICY)),
            new Item("Phasing out certain pesticide uses is necessary to protect pollinators and biodiversity.", List.of(DebateCategory.ENVIRONMENT, DebateCategory.TECHNOLOGY)),
            new Item("Citizens should be able to opt out of targeted political advertising.", List.of(DebateCategory.POLICY)),
            new Item("Net neutrality protections must be reinstated and enforced.", List.of(DebateCategory.POLICY)),
            new Item("Remote work should be a legal right for employees in high-cost cities.", List.of(DebateCategory.POLICY)),
            new Item("Cities should implement congestion pricing to reduce traffic and pollution.", List.of(DebateCategory.POLICY)),
            new Item("Schools should delay start times to match adolescent sleep patterns.", List.of(DebateCategory.EDUCATION)),
            new Item("Governments should support the transition to plant-based agricultural subsidies.", List.of(DebateCategory.POLICY)),
            new Item("Commercial space mining should be open to private companies under international law.", List.of(DebateCategory.POLICY)),
            new Item("The gig economy should provide minimum benefits and protections to workers.", List.of(DebateCategory.POLICY)),
            new Item("Decriminalizing certain low-risk drugs would reduce incarceration rates.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Online platforms must take stronger action against misinformation.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Reforming pharmaceutical pricing is necessary to ensure medicines are affordable.", List.of(DebateCategory.POLICY)),
            new Item("Universal healthcare should be funded through progressive taxation.", List.of(DebateCategory.POLICY)),
            new Item("National service should be an option but not a legal requirement for citizens.", List.of(DebateCategory.POLICY)),
            new Item("Cities should eliminate parking minimums to encourage sustainable development.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Governments should mandate circular product design to reduce waste.", List.of(DebateCategory.POLICY)),
            new Item("Internet access is a basic human right and should be provided universally.", List.of(DebateCategory.POLICY)),
            new Item("Taxing meat could be an effective policy to reduce environmental harm.", List.of(DebateCategory.ENVIRONMENT)),
            new Item("A four-day work week increases productivity and should be adopted widely.", List.of(DebateCategory.POLICY)),
            new Item("Paid parental leave should be mandated for all employers above a size threshold.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Cryptocurrencies should be regulated as legal tender by national governments.", List.of(DebateCategory.POLICY)),
            new Item("Corporate boards must meet minimum diversity requirements by law.", List.of(DebateCategory.POLICY)),
            new Item("Single-use plastics should be phased out through legislation and incentives.", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Public funding should prioritize space exploration projects with public benefit.", List.of(DebateCategory.POLICY)),
            new Item("Regulations are needed to prevent exploitative data collection by smart devices.", List.of(DebateCategory.POLICY)),
            new Item("A national AI safety agency should oversee high-risk AI deployments.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Mandatory ID for social media would improve accountability at the cost of privacy.", List.of(DebateCategory.POLICY)),
            new Item("Establishing a universal digital ID offers benefits but risks centralization of power.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Public policy should encourage citizen assemblies for major ethical questions.", List.of(DebateCategory.ETHICS)),
            new Item("Legislation should limit the length and scope of software patents to foster innovation.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Regulations should reduce single-use packaging across retail industries.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Governments should subsidize plant-based alternatives to reduce emissions.", List.of(DebateCategory.POLICY)),
            new Item("Mandatory labeling for environmental impact should apply to consumer products.", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Restrictions on workplace surveillance protect employee privacy and dignity.", List.of(DebateCategory.POLICY)),
            new Item("Public debate should determine the ethical boundaries for human gene editing.", List.of(DebateCategory.ETHICS)),
            new Item("Civil society should have stronger roles in shaping platform content moderation rules.", List.of(DebateCategory.POLICY)),
            new Item("Phasing out internal combustion engines should be mandatory over a set timetable.", List.of(DebateCategory.POLICY)),
            new Item("Standardized testing remains a necessary measure for educational accountability.", List.of(DebateCategory.EDUCATION, DebateCategory.TECHNOLOGY)),
            new Item("Governments should fund retraining programs for workers displaced by automation.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("The right to repair medical devices should be protected to improve healthcare access.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Mandatory labeling should identify media that is fully or partially AI-generated.", List.of(DebateCategory.ETHICS, DebateCategory.TECHNOLOGY)),
            new Item("Cashless societies risk excluding vulnerable populations and should be avoided.", List.of(DebateCategory.POLICY)),
            new Item("Countries should adopt uniform rules for AI transparency in public services.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Financial transaction taxes could reduce speculative trading without harming growth.", List.of(DebateCategory.POLICY)),
            new Item("Banning microtargeted political ads would improve democratic discourse.", List.of(DebateCategory.POLICY)),
            new Item("Private companies should not be allowed to collect biometric data without consent.", List.of(DebateCategory.POLICY)),
            new Item("Limits on surveillance advertising are necessary to protect consumers.", List.of(DebateCategory.POLICY)),
            new Item("Facial recognition technology should be banned from public law enforcement use.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Consumers should have a legal right to repair their electronic devices.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Limits on government data retention are necessary to protect privacy.", List.of(DebateCategory.POLICY)),
            new Item("Algorithmic hiring tools require independent auditing before use.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Commercialization of heritage sites should be limited to preserve cultural value.", List.of(DebateCategory.POLICY)),
            new Item("Mandatory corporate reporting on climate risks should be audited externally.", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Governments should require carbon border adjustment tariffs to protect industry.", List.of(DebateCategory.ENVIRONMENT)),
            new Item("The state should provide universal childcare to support working families.", List.of(DebateCategory.POLICY)),
            new Item("Governments should regulate influencer advertising aimed at minors.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Large technology companies should be broken up to restore market competition.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Regulations should prevent microtargeting in political campaigns.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Publicly funded research should prioritize biodiversity and conservation efforts.", List.of(DebateCategory.ENVIRONMENT)),
            new Item("A universal basic income provides a better safety net than current welfare systems.", List.of(DebateCategory.POLICY)),
            new Item("Schools should teach digital literacy as part of the core curriculum.", List.of(DebateCategory.EDUCATION, DebateCategory.TECHNOLOGY)),
            new Item("Research into climate geoengineering should be publicly funded and regulated.", List.of(DebateCategory.ENVIRONMENT)),
            new Item("Education systems should reduce emphasis on standardized tests and increase project-based learning.", List.of(DebateCategory.EDUCATION)),
            new Item("Public broadband access should be expanded as public infrastructure.", List.of(DebateCategory.POLICY)),
            new Item("Algorithms used in policing should be subject to public oversight and transparency.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Automation should be taxed to fund retraining programs for displaced workers.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Public transport should be free in major metropolitan areas.", List.of(DebateCategory.POLICY)),
            new Item("Using gene drives to control invasive species is an acceptable environmental tool.", List.of(DebateCategory.ENVIRONMENT, DebateCategory.ETHICS)),
            new Item("Legal recognition of digital identities must balance convenience and security.", List.of(DebateCategory.TECHNOLOGY)),
            new Item("Mandatory corporate climate disclosures should be standardized internationally.", List.of(DebateCategory.ENVIRONMENT))
    );
}
